services:
  postgres:
    container_name: postgres_audio_to_text
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#  backend:
#    image: macchiato23/audio-to-text-be:latest
#    container_name: audio_to_text_backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#      DATABASE_USER: ${DATABASE_USER}
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#    networks:
#      - postgres
#    depends_on:
#      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: