spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:audio_to_text}
    password: ${DATABASE_PASSWORD:password}
    username: ${DATABASE_USER:postgres}
    hikari:
      connection-timeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000