spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:audio_to_text}
    password: ${DATABASE_PASSWORD:password}
    username: ${DATABASE_USER:default}